language: c
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: clang
    sudo: required
    cache: apt
  - os: osx
    compiler: clang
before_install:
- openssl aes-256-cbc -K $encrypted_4867891545ea_key -iv $encrypted_4867891545ea_iv -in game_rsa.enc -out game_rsa -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential
  libsdl2-dev libsdl2-net-dev; fi
install: true
script: make client && make server && make site
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ./build/client && tar -zcvf game-linux-$(cat
  ../../version.txt).tar.gz linux && cd ../..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ./build/server && tar -zcvf game-server-$(cat
  ../../version.txt).tar.gz linux && cd ../..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -zcvf game-site-$(cat version.txt).tar.gz
  web; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ./build/client && zip -r -X ./game-osx-$(cat
  ../../version.txt).zip osx && cd ../..; fi
deploy:
- provider: releases
  api_key:
    secure: FouxsgKutb/aObfMIHU4spLb976dtjcoPHCSgJ5jOV3eO8dCs/943fxZkXmBzt7/Zn1DLZ9suTMFvL0Ucmh/Z0Nmy5eBC/GS1vAQdLOVeX8NEEikznJbw5XkFbyrOCLNL4tXsk4tNndliGneWD3TUc/bTFf13/s89AEaB0OStTcddIfPaDrBxNudiqVSFH+Yyz8ZloWBvtsBumY1K558qaIXSDLTsDXUPYqRbO6XFLUeklw2+6XI7duVV92bjODIPDZb2LlAsdYS+e9xjhLjwBHNAPQMj3pQBwOP1HOEwnqGpQhPfobW7ywoXqGvJ52AvSHlcJ9N4rv/hsNH5oDUBnB0YLAmxHIUmmCifSu8+krQ784KPUroFQMfj3PuZzEC1aCBj886OxVdARBPl7S96Z7OZCZO0keEFXMuUjyimGcVxR1S8fXfcGrt3rQJTKmDNHZK5ghtuXx1UXseAaRZvFmd/zNsQ40nDGQ04OGgBdvNUR/hfBfWhbQ+fzdqnmugOCV5L97B23189HtmLAkIbCQmzCDcDzJvkvG1SV6n5jo4pmkZUeOFoYyki92kLE1rMb8ZvT9MED4hjVcX2aU5qLIJxpCjMPc+AcTZ7/tafeg6iK/G1tSeNrIetzDHeYyV2pvUR338R1Frc4JOm2Q71HTlCedS9AuYHvQn0s9B0IQ=
  file:
  - build/client/game-linux-$(cat version.txt).tar.gz
  - build/server/game-server-$(cat version.txt).tar.gz
  - game-site-$(cat version.txt).tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: saolsen/game
    condition: $TRAVIS_OS_NAME == linux
- provider: releases
  api_key:
    secure: FouxsgKutb/aObfMIHU4spLb976dtjcoPHCSgJ5jOV3eO8dCs/943fxZkXmBzt7/Zn1DLZ9suTMFvL0Ucmh/Z0Nmy5eBC/GS1vAQdLOVeX8NEEikznJbw5XkFbyrOCLNL4tXsk4tNndliGneWD3TUc/bTFf13/s89AEaB0OStTcddIfPaDrBxNudiqVSFH+Yyz8ZloWBvtsBumY1K558qaIXSDLTsDXUPYqRbO6XFLUeklw2+6XI7duVV92bjODIPDZb2LlAsdYS+e9xjhLjwBHNAPQMj3pQBwOP1HOEwnqGpQhPfobW7ywoXqGvJ52AvSHlcJ9N4rv/hsNH5oDUBnB0YLAmxHIUmmCifSu8+krQ784KPUroFQMfj3PuZzEC1aCBj886OxVdARBPl7S96Z7OZCZO0keEFXMuUjyimGcVxR1S8fXfcGrt3rQJTKmDNHZK5ghtuXx1UXseAaRZvFmd/zNsQ40nDGQ04OGgBdvNUR/hfBfWhbQ+fzdqnmugOCV5L97B23189HtmLAkIbCQmzCDcDzJvkvG1SV6n5jo4pmkZUeOFoYyki92kLE1rMb8ZvT9MED4hjVcX2aU5qLIJxpCjMPc+AcTZ7/tafeg6iK/G1tSeNrIetzDHeYyV2pvUR338R1Frc4JOm2Q71HTlCedS9AuYHvQn0s9B0IQ=
  file: ./build/client/game-osx-$(cat version.txt).zip
  skip_cleanup: true
  on:
    tags: true
    repo: saolsen/game
    condition: $TRAVIS_OS_NAME == osx
- provider: script
  script: scripts/deploy_server.sh
  on:
    tags: true
    repo: saolsen/game
