dist:
    - trusty
language: c
compiler: clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential libsdl2-dev libsdl2-net-dev
install: true
script: make client && make server
