language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
      cache: apt
    - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq  ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential libsdl2-dev libsdl2-net-dev  ; fi

install: true
script: make client && make server
